version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    registries:
      - npm-ghp-ftg
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly