import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import type { Metadata } from "next";
import { Manrope } from "next/font/google";

import { Footer, Navigation } from "@/global/components";

import "./globals.css";

const manrope = Manrope({
  subsets: ["latin", "latin-ext"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NEXT_PUBLIC_GAID = process.env.NEXT_PUBLIC_GAID || "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={manrope.className}>
        <div>
          <main className="relative overflow-hidden z-10 bg-brand-black">
            <Navigation />
            {children}
          </main>
          <Footer />
        </div>
      </body>
      <GoogleAnalytics gaId={NEXT_PUBLIC_GAID} />
    </html>
  );
}
