import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import { Contact, Navigation } from "@/global/components";

import "./globals.css";

const poppins = Poppins({
  subsets: ["devanagari", "latin", "latin-ext"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const NEXT_PUBLIC_GAID = process.env.NEXT_PUBLIC_GAID || "";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={poppins.className}>
        <Navigation />
        {children}
        <Contact />
      </body>
      <GoogleAnalytics gaId={NEXT_PUBLIC_GAID} />
    </html>
  );
}
